// Generated by CoffeeScript 2.7.0
(function() {
  // Define a function to update the time
  var updateTime;

  updateTime = function() {
    var hours, minutes, now, seconds, timeString;
    now = new Date();
    hours = now.getHours();
    minutes = now.getMinutes();
    seconds = now.getSeconds();
    timeString = `${hours}:${minutes}:${seconds}`;
    return document.getElementById("time").textContent = timeString;
  };

  // Call the updateTime function initially to set the time
  updateTime();

  // Update the time every second
  setInterval(updateTime, 1000);

}).call(this);
