// Generated by CoffeeScript 2.7.0
(function() {
  // This is a simple CoffeeScript code
  var greet;

  greet = function(name) {
    return alert(`Hello, ${name}!`);
  };

  // Call the greet function
  greet("World");

}).call(this);
